export const projects = [
  {
    id: 1,
    title: "Casa California",
    editorial_name: "California",
    intervention_type: "Obra incompleta",
    location: "Misantla, Veracruz",
    year: "2019",
    narrative_intro: "El lujo convive con sensaciones.",
    description: "Un domo de cristal que da la bienvenida a la luz y recibe con calidez a quien llegue. Los acabados de pecho paloma adornan las ventanas, muros y escaleras. En el Patio Mayor: jardín, alberca y asador invitan a la convivencia y a la celebración. Una casa donde la armonía habita con elegancia.",
    cover: "/images/project_california/cali1.jpeg",
    gallery: [
      "/images/project_california/cali1.jpeg",
      "/images/project_california/cali2.jpeg",
      "/images/project_california/cali3.jpeg",
      "/images/project_california/cali4.jpeg",
      "/images/project_california/cali5.jpeg",
      "/images/project_california/cali6.jpeg",
      "/images/project_california/cali7.jpeg",
      "/images/project_california/cali8.jpeg",
      "/images/project_california/california_alta.mp4",
      "/images/project_california/california_baja.mp4"
    ]
  },
  {
    id: 2,
    title: "Casa Caturra",
    editorial_name: "Caturra",
    intervention_type: "Obra completa",
    location: "Coatepec, Veracruz",
    year: "2015",
    narrative_intro: "Calor y luz que abrazan.",
    description: "Su jardín interior funciona como eje y corazón del proyecto. Un muro llorón que, al caer el agua, nos recuerda el fluir de la vida. La chimenea brinda el calor y cercanía en ambos niveles. Una casa que te abraza con calidez.",
    cover: "/images/project_caturra/catu1.jpeg",
    gallery: [
      "/images/project_caturra/catu1.jpeg",
      "/images/project_caturra/catu2.jpeg",
      "/images/project_caturra/catu3.jpeg",
      "/images/project_caturra/catu4.jpeg",
      "/images/project_caturra/catu5.jpeg",
      "/images/project_caturra/catu6.jpeg",
      "/images/project_caturra/catu7.jpeg",
      "/images/project_caturra/catu8.jpeg",
      "/images/project_caturra/catu9.jpeg",
      "/images/project_caturra/caturra_alta.mp4",
       "/images/project_caturra/caturra_baja.mp4"
    ]
  },
  {
    id: 3,
    title: "Casa Maya",
    editorial_name: "Maya",
    intervention_type: "Obra incompleta",
    location: "Estanzuela, Veracruz",
    year: "2024",
    narrative_intro: "Una única planta como gesto de comodidad y cercanía.",
    description: "El diseño está pensado para que la casa respire a través de los jardines: frontal, interior y trasero. Las piezas permiten lo esencial de la vida a través de la iluminación y ventilación natural. Una casa que reúne lo esencial sin renunciar a las sensaciones. En Maya es dejar que la luz, el aire y el jardín ordenen la vida.",
    cover: "/images/project_maya/maya1.jpeg",
    gallery: [
      "/images/project_maya/maya1.jpeg",
      "/images/project_maya/maya2.jpeg",
      "/images/project_maya/maya3.jpeg",
      "/images/project_maya/maya4.jpeg",
      "/images/project_maya/maya5.jpeg",
      "/images/project_maya/maya6.jpeg",
      "/images/project_maya/maya7.jpeg",
      "/images/project_maya/maya8.jpeg",
      "/images/project_maya/maya9.jpeg",
      "/images/project_maya/maya10.jpeg",
      "/images/project_maya/maya.mp4",
    ]
  },
  {
    id: 4,
    title: "Casa Palapa",
    editorial_name: "Palapa",
    intervention_type: "Proyección arquitectónica",
    location: "Boquilla de Oro, Veracruz",
    year: "2024",
    narrative_intro: "Descanso y disfrute a pocos metros del mar.",
    description: "La brisa marina entra por el balcón. El Roof Garden eleva la vista y el rumor de las olas enamora con su armonía sonora. El diseño protege la calma y a la palapa donde inicia todo. Una casa donde el mar descansa contigo.",
    cover: "/images/project_palapa/pala1.jpeg",
    gallery: [
      "/images/project_palapa/pala1.jpeg",
      "/images/project_palapa/pala2.jpeg",
      "/images/project_palapa/pala3.jpeg",
      "/images/project_palapa/pala4.jpeg",
      "/images/project_palapa/palapa_alta.mp4",
      "/images/project_palapa/palapa_baja.mp4"
    ]
  },
  {
    id: 5,
    title: "Casa Piñón",
    editorial_name: "Piñón",
    intervention_type: "Obra incompleta",
    location: "Las Vigas, Veracruz",
    year: "2022",
    narrative_intro: "Una experiencia que protege y se integra al paisaje.",
    description: "Su diseño está inspirado en el estilo nórdico. El interior nos brinda texturas de madera y el entorno el aroma a pino. Dos plantas que permiten conexión y contemplación. La armonía se expresa en la luz tamizada que dibuja patrones sobre suelos de madera. Una casa que convive con el bosque.",
    cover: "/images/project_pinon/pinion1.jpeg",
    gallery: [
      "/images/project_pinon/pinion1.jpeg",
      "/images/project_pinon/pinion2.jpeg",
      "/images/project_pinon/pinion3.jpeg",
      "/images/project_pinon/pinion4.jpeg",
      "/images/project_pinon/pinion5.jpeg",
      "/images/project_pinon/pinion6.jpeg",
      "/images/project_pinon/pinion7.jpg",
      "/images/project_pinon/pinion8.jpeg",
      "/images/project_pinon/pinion9.jpeg",
      "/images/project_pinon/pinion_alta.mp4",
      "/images/project_pinon/pinion_baja.mp4"
    ]
  }
];